# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-15 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.CharField(default='00', max_length=150, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='00', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(default='00', max_length=200, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='00', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default='00', verbose_name='Nº'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, verbose_name='Telefone'),
        ),
    ]
