# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Imagens do produto'},
        ),
    ]
