# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-05 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180506_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100, null=True, verbose_name='Tamanho'),
        ),
    ]
