# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180713_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=100, null=True, verbose_name='Tamanho'),
        ),
    ]
